import {HighlightText} from "@/libs/HighlightText/HighlightText";
import SyntaxHighlighter from "react-syntax-highlighter";
import {dracula} from "react-syntax-highlighter/dist/esm/styles/hljs";
import {ButtonSecondary} from "@/libs/buttons/button";
import {Metadata} from "next";

export const metadata: Metadata = {
    title: 'C- ব্রেক এবং কন্টিনিউ',
    description: 'Generated by Sajib Ahmed',
}
const CBreakContinue = () => {

    const codeString = '#include<stdio.h>\n' +
        'int main(){\n' +
        '    int i=1,j=1;//initializing a local variable\n' +
        ' \n' +
        '    for(i=1;i<=3;i++){\n' +
        '        for(j=1;j<=3;j++){\n' +
        ' \n' +
        '            printf("%d %d\\n",i,j);\n' +
        ' \n' +
        '            if(i==2 && j==2){\n' +
        '                break;//will break loop of j only\n' +
        '        }\n' +
        '    }   //end of for loop\n' +
        '    return 0;\n' +
        '    }\n' +
        '}'


    const codeString2 = '#include<stdio.h>\n' +
        'int main(){\n' +
        'int i = 0;\n' +
        '\n' +
        'while (i < 10) {\n' +
        '  if (i == 4) {\n' +
        '    i++;\n' +
        '    continue;\n' +
        '  }\n' +
        '  printf("%d\\n", i);\n' +
        '  i++;\n' +
        '}'+
        '    return 0;\n' +
        '    }\n' +
        '}'




    return(
        <div  className="">
            <h2 className="H3 md-space-bottom">আজকে আমরা C প্রোগ্রামিংয়ের অন্যতম গুরুত্বপূর্ণ একটি টপিক ব্রেক এবং কন্টিনিউ সম্পর্কে জানবো।</h2>
            <p className="Primary-paragraph md-space-bottom">
                <HighlightText highlightText={"break;"}/> ব্রেক এবং  <HighlightText highlightText={"continue;"}/> কন্টিনিউ হচ্ছে কিওয়ার্ড। সি ল্যাংগুয়েজে কন্টিনিউ স্টেটমেন্ট ব্যবহার করা হয় কন্ডিশন কন্টোল করে লুপ চালিয়ে যাওয়ার জন্য এবং ব্রেক স্টেটমেন্ট ব্যবহার করা হয় কন্ডিশন কন্টোল করে লুপ বন্ধ করার জন্য।
            </p>
            <h3 className="H4">C ব্রেক স্টেটমেন্ট</h3>
            <p className="Primary-paragraph md-space-bottom">
                ব্রেক (break) সি ল্যংগুয়েজ এর একটি কিওয়ার্ড যা কোন চলন্ত লুপ থেকে বের হতে ব্যবহার করা হয়।

                ব্রেক স্টেটমেন্ট দ্বারা লুপ থেকে একটি, একটি করে বের হওয়া যায়।

                নেস্টেড লুপ এর ক্ষেত্রে প্রথম ভিতরের লুপ থেকে বের হবে তারপর বাহিরের লুপ প্রসেস করবে।
            </p>
            <p className="Primary-paragraph md-space-y">
                নিচের উদাহরণটি দেখুনঃ
            </p>
            <div className="sm-space-y">
                <SyntaxHighlighter language="c" style={dracula}>
                    {codeString}
                </SyntaxHighlighter>
            </div>
            <h3 className="H4">C কন্টিনিউ স্টেটমেন্ট</h3>
            <p className="Primary-paragraph md-space-y">
                কন্টিনিউ একটি কিওয়ার্ড। সি ল্যাংগুয়েজে কন্টিনিউ স্টেটমেন্ট ব্যবহার করা হয় কন্ডিশন কন্টোল করে লুপ চালিয়ে যাওয়ার জন্য।

                কন্টিনিউ স্টেটমেন্ট লুপের ভিতরের কিছু লাইনকে স্কিপ করে সামনের ইটারেশনটি চালিয়ে যায়।
            </p>
            <p className="Primary-paragraph md-space-y">
                নিচের উদাহরণটি দেখুনঃ
            </p>
            <div className="">
                <SyntaxHighlighter language="c" style={dracula}>
                    {codeString2}
                </SyntaxHighlighter>
            </div>


            <div className="navigate-buttons-style">
                <ButtonSecondary btnLink={"/c_for_loop"} btnText={"❮ পূর্ববর্তী অধ্যায়"}/>
                <ButtonSecondary btnLink={"/c_arrays"} btnText={"পরবর্তী অধ্যায় ❯"}/>
            </div>
        </div>
    )
}

export  default CBreakContinue