import { Navbar } from '@/components/Navbar';
import {CSideBarLogo} from "@/components/CSideBarLogo";
import {Metadata} from "next";


export const metadata: Metadata = {
    // @ts-ignore
    title: {
        default: 'C-বাংলা'
    },
    template: "%s  | C-বাংলা",
    description: 'Generated by Sajib Ahmed',
}
export default function DashboardLayout({children,}: { children: React.ReactNode; }) {
    return (
        <>
            <Navbar />
            <div className="lg:flex lg:items-center lg:justify-center relative">
                <CSideBarLogo />
                <div className="w-full lg:w-[78%] xl:w-[85%] h-screen overflow-auto px-[16px] md:px-[24px] lg:px-[32px] py-[100px]">
                    {children}
                </div>
            </div>
        </>
    );
}
