import type { Metadata } from 'next'
import {Josefin_Sans,Jost } from 'next/font/google'
import './globals.css'

const josefin_sans= Josefin_Sans({ subsets: ['latin'] })
const jost= Jost({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by Sajib Ahmed',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${josefin_sans.className}${jost.className}`}> {children}</body>
    </html>
  )
}
