import type { Metadata } from 'next'
import {Josefin_Sans, Jost, Noto_Sans_Bengali} from 'next/font/google'
import './globals.css'

const josefin_sans= Josefin_Sans({ subsets: ['latin'] })
const Not_Sans= Noto_Sans_Bengali({ subsets: ['latin'] })

export const metadata: Metadata = {
  // @ts-ignore
  title: {
    default: 'বাংলায় কোডিং'
  },
  template: "%s || বাংলায় কোডিং",
  description: 'Generated by Sajib Ahmed',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${josefin_sans.className}${Not_Sans.className}`}> {children}</body>
    </html>
  )
}
