import type { Metadata } from 'next'
import { Jost,Josefin_Sans } from 'next/font/google'
import './globals.css'

const jost= Jost({ subsets: ['latin'] })
const josefin_sans= Josefin_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by Sajib Ahmed',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${jost.className}${josefin_sans.className}`}>{children}</body>
    </html>
  )
}
