export const c_sidebar = [
    { id: '1', textLink: '#', text: 'C Tutorial' },
    { id: '2', textLink: '/c_home', text: 'C হোম'},
    { id: '3', textLink: '/c_introduction', text: 'C ইন্ট্রোডাকশন' },
    { id: '4', textLink: '/c_get_started', text: 'C শুরু করি'},
    { id: '5', textLink: '/c_syntax', text: 'C সিনট্যাক্স'},
    { id: '6', textLink: '/c_output', text: 'C আউটপুট' },
    { id: '7', textLink: '/c_comments', text: 'C কমেন্টস' },
    { id: '8', textLink: '/c_variables', text: 'C ভ্যরিয়েবলস' },
    { id: '9', textLink: '/c_data_types', text: 'C ডাটা টাইপস' },
    { id: '10', textLink: '/c_constants', text: 'C কন্সটেন্স' },
    { id: '11', textLink: '/c_operator', text: 'C অপারেটরস' },
    { id: '12', textLink: '/c_boolean', text: 'C বুলিয়ান' },
    { id: '13', textLink: '/c_if_else', text: 'C ইফ...ইলস' },
    { id: '14', textLink: '/c_switch', text: 'C সুইচ' },
    { id: '15', textLink: '/c_while_loop', text: 'C হুয়াইল লুপ' },
    { id: '16', textLink: '/c_for_loop', text: 'C ফর লুপ' },
    { id: '17', textLink: '/c_break_continue', text: 'C ব্রেক/কন্টিনিউ' },
    { id: '18', textLink: '/c_arrays', text: 'C অ্যারে' },
    { id: '19', textLink: '/c_strings', text: 'C স্ট্রিং' },
    { id: '20', textLink: '/c_user_input', text: 'C ইউজার ইনপুট' },
    { id: '21', textLink: '/c_memory_address', text: 'C মেমোরি এড্রেস' },
    { id: '22', textLink: '/c_pointer', text: 'C পয়েন্টার' },
    { id: '23', textLink: '#', text: 'C Functions' },
    { id: '24', textLink: '/c_functions', text: 'C Functions' },
    { id: '25', textLink: '/c_function_parameters', text: 'C Function Parameters' },
    { id: '26', textLink: '/c_function_declaration', text: 'C Function Declaration' },
    { id: '27', textLink: '/c_recursion', text: 'C Recursion' },
    { id: '28', textLink: '/c_math_functions', text: 'C Math Functions' },
    { id: '29', textLink: '/c_files', text: 'C Files' },
    { id: '30', textLink: '/c_create_files', text: 'C Create Files' },
    { id: '31', textLink: '/c_write_files', text: 'C Write To Files' },
    { id: '32', textLink: '/c_read_files', text: 'C Read Files' },
    { id: '33', textLink: '#', text: 'C Structures' },
    { id: '34', textLink: '/c_structures', text: 'C Structures' },
    { id: '35', textLink: '#', text: 'C Enums' },
    { id: '36', textLink: '/c_enums', text: 'C Enums' },
    { id: '37', textLink: '#', text: 'C Examples' },
    { id: '38', textLink: '/c_exercises', text: 'C Exercises' },
    { id: '39', textLink: '/c_quiz', text: 'C Quiz' },
    { id: '40', textLink: '/c_compiler', text: 'C Compiler' },
    { id: '41', textLink: '/c_certificate', text: 'C Certificate' },
];


